using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Coplt.Analyzers.Utilities;
using Microsoft.CodeAnalysis;

namespace Coplt.Analyzers.Generators.Templates;

public readonly partial record struct GenBase(
    string RawFullName,
    NullableContextOptions Nullable,
    HashSet<string> Usings,
    ImmutableList<NameWrap>? Parents,
    NameWrap Target
)
{
    public string FileFullName { get; } = RawFullName.Replace('<', '[').Replace('>', ']');
}

public abstract partial class ATemplate(
    GenBase GenBase
)
{
    public GenBase GenBase = GenBase;

    public string FullName { get; } = $"global::{GenBase.RawFullName}";
    public string TypeName { get; } = GenBase.RawFullName.Split('.').Last();

    protected StringBuilder sb = new();

    protected abstract void DoGen();
    protected virtual void DoGenFileScope() { }

    private void AddNullable()
    {
        sb.AppendLine("#nullable disable warnings");
        sb.AppendLine("#nullable enable annotations");
        sb.AppendLine();
    }

    private void AddUsings()
    {
        foreach (var use in GenBase.Usings)
        {
            sb.AppendLine(use);
        }
        if (GenBase.Usings.Count > 0) sb.AppendLine();
    }

    private void AddNameWrapPre()
    {
        if (GenBase.Parents != null)
        {
            foreach (var wrap in GenBase.Parents)
            {
                sb.Append(wrap.Code);
                sb.AppendLine(" {");
            }
        }
    }

    private void AddNameWrapPost()
    {
        if (GenBase.Parents != null)
        {
            foreach (var wrap in GenBase.Parents.Reverse())
            {
                sb.Append("} // ");
                sb.AppendLine(wrap.Code);
            }
        }
    }

    public string Gen()
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        AddNullable();
        AddUsings();
        AddNameWrapPre();
        sb.AppendLine();
        DoGen();
        sb.AppendLine();
        AddNameWrapPost();
        DoGenFileScope();
        return sb.ToString();
    }
}
